/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-12-03 05:53:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mainUI;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    /* ========================================= */\r\n");
      out.write("    /* 핵심 수정: flex: 1 추가 (남은 공간 모두 차지) */\r\n");
      out.write("    /* ========================================= */\r\n");
      out.write("    .main-content-area {\r\n");
      out.write("        flex: 1;  /* 이 속성이 있어야 사이드바 옆 남은 공간을 꽉 채웁니다 */\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center; /* 가로 중앙 정렬 */\r\n");
      out.write("        align-items: center;     /* 세로 중앙 정렬 */\r\n");
      out.write("        height: 100vh;           /* 화면 전체 높이 */\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        background-color: #181818; /* 배경색 지정 (혹시 투명일 경우 대비) */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-card {\r\n");
      out.write("        margin-top: 50px; /* 상단 마진 추가 */\r\n");
      out.write("        background: #1F1F1F;\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.4);\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 450px; /* 폼 최대 너비 */\r\n");
      out.write("        margin: 0; /* 마진 초기화 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 반응형: 화면이 좁아져서 사이드바가 사라지거나 줄어들 때 */\r\n");
      out.write("    @media screen and (max-width: 992px) {\r\n");
      out.write("        .main-content-area {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 기타 스타일 (기존 유지) */\r\n");
      out.write("    .auth-card h2 {\r\n");
      out.write("        color: white;\r\n");
      out.write("        border-bottom: 2px solid #34C759;\r\n");
      out.write("        padding-bottom: 10px;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        font-size: 26px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group { margin-bottom: 20px; }\r\n");
      out.write("    .form-group label { display: block; margin-bottom: 8px; font-weight: 500; color: #AAAAAA; }\r\n");
      out.write("    .form-group input {\r\n");
      out.write("        width: 100%; padding: 12px; border: 1px solid #333;\r\n");
      out.write("        border-radius: 5px; background: #2A2A2A; color: white;\r\n");
      out.write("        box-sizing: border-box; font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("    .highlight-button {\r\n");
      out.write("        width: 100%; padding: 12px; border: none; border-radius: 5px;\r\n");
      out.write("        background: #34C759; color: white; font-size: 17px; font-weight: 700;\r\n");
      out.write("        cursor: pointer; transition: background 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .highlight-button:hover { background: #30A84E; }\r\n");
      out.write("    .auth-card p { text-align: center; margin-top: 20px; }\r\n");
      out.write("    .highlight-link { color: #34C759; text-decoration: none; font-weight: 600; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"page-layout\">\r\n");
      out.write("        \r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"main-content-wrapper\">\r\n");
      out.write("            <div class=\"main-content-area\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"auth-card\">\r\n");
      out.write("                    <h2><span class=\"highlight\">로그인</span></h2>\r\n");
      out.write("                    <form action=\"login.do\" method=\"post\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"email\">이메일:</label>\r\n");
      out.write("                            <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"이메일 주소를 입력하세요\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"password\">비밀번호:</label>\r\n");
      out.write("                            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"비밀번호를 입력하세요\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\" style=\"margin-top: 30px;\">\r\n");
      out.write("                            <button type=\"submit\" class=\"highlight-button\">로그인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("                    <p>계정이 없으신가요? <a href=\"signupForm.do\" class=\"highlight-link\">회원가입</a></p>\r\n");
      out.write("                    ");

                        String errorMessage = (String) request.getAttribute("errorMessage");
                        if (errorMessage != null) {
                    
      out.write("\r\n");
      out.write("                        <p style=\"color:#FF3B30;\">");
      out.print( errorMessage );
      out.write("</p>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Footer Include -->\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
