/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-12-03 11:22:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.song;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class albumDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764653109889L));
    _jspx_dependants.put("jar:file:/C:/Users/kms88/OneDrive/바탕%20화면/Coding%20File/Project/BackendProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MainUIsample/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.albumName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" - WaterMelon</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .album-modal-overlay {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.85);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-modal-content {\r\n");
      out.write("            background: #1E1E1E;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 900px; /* Adjusted for album content */\r\n");
      out.write("            height: 90%;\r\n");
      out.write("            max-height: 800px;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);\r\n");
      out.write("            animation: modalSlideUp 0.3s ease;\r\n");
      out.write("            overflow-y: auto; /* Enable scrolling for content */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes modalSlideUp {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: translateY(50px);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .modal-close-btn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            z-index: 10000;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .modal-close-btn:hover {\r\n");
      out.write("            background: #ff3b30;\r\n");
      out.write("            transform: rotate(90deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Styles from original albumDetail.jsp, adapted for modal content */\r\n");
      out.write("        .album-detail-modal-container { /* Renamed from .album-detail-container to avoid conflict */\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 40px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            background: #1E1E1E;\r\n");
      out.write("            padding: 0; /* No extra padding here, already in modal-content */\r\n");
      out.write("            border-radius: 0; /* No extra border-radius here */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-cover {\r\n");
      out.write("            width: 200px; /* Smaller in modal */\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-info {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-type {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-title {\r\n");
      out.write("            font-size: 38px; /* Smaller in modal */\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-artist {\r\n");
      out.write("            font-size: 20px; /* Smaller in modal */\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .album-meta {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .meta-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tracks-section {\r\n");
      out.write("            background: #1E1E1E;\r\n");
      out.write("            border-radius: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tracks-header {\r\n");
      out.write("            font-size: 24px; /* Smaller in modal */\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("            border-bottom: 1px solid #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-item:hover {\r\n");
      out.write("            background: #282828;\r\n");
      out.write("            transform: translateX(5px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-number {\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-info {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-title {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-bottom: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-artist {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-duration {\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-play-icon {\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            background: #34C759;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transition: opacity 0.3s ease;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .track-item:hover .track-play-icon {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"album-modal-overlay\" onclick=\"closeModal(event)\">\r\n");
      out.write("        <div class=\"album-modal-content\" onclick=\"event.stopPropagation()\">\r\n");
      out.write("            <button class=\"modal-close-btn\" onclick=\"window.history.back()\">&times;</button>\r\n");
      out.write("            \r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "albumDetailModalContent.jsp", out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        function closeModal(event) {\r\n");
      out.write("            if (event.target.classList.contains('album-modal-overlay')) {\r\n");
      out.write("                window.history.back();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
