/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-12-03 13:07:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.song;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class songDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764653109889L));
    _jspx_dependants.put("jar:file:/C:/Users/kms88/OneDrive/바탕%20화면/Coding%20File/Project/BackendProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MainUIsample/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>노래 상세 - ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .song-modal-overlay {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.85);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-modal-content {\r\n");
      out.write("            background: #1E1E1E;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);\r\n");
      out.write("            animation: modalSlideUp 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes modalSlideUp {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: translateY(50px);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .modal-close-btn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .modal-close-btn:hover {\r\n");
      out.write("            background: #ff3b30;\r\n");
      out.write("            transform: rotate(90deg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-detail-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-album-art {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);\r\n");
      out.write("            animation: albumRotate 20s linear infinite paused;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-album-art.playing {\r\n");
      out.write("            animation-play-state: running;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes albumRotate {\r\n");
      out.write("            from { transform: rotate(0deg); }\r\n");
      out.write("            to { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-info-section {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-detail-title {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-detail-artist {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .song-metadata {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .metadata-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .metadata-label {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .metadata-value {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #34C759;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .player-controls {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .play-pause-btn {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            background: #34C759;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin: 0 auto 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .play-pause-btn:hover {\r\n");
      out.write("            background: #2ba84d;\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(52, 199, 89, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .progress-bar-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 6px;\r\n");
      out.write("            background: #333;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .progress-bar {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: #34C759;\r\n");
      out.write("            width: 0%;\r\n");
      out.write("            transition: width 0.1s linear;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .time-display {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .spotify-embed {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .action-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-top: 25px;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .action-button {\r\n");
      out.write("            padding: 12px 25px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-add-playlist {\r\n");
      out.write("            background: #0E9EEF;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-add-playlist:hover {\r\n");
      out.write("            background: #0c89d1;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-add-favorite {\r\n");
      out.write("            background: #ff3b30;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-add-favorite:hover {\r\n");
      out.write("            background: #e6352b;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        /* New style for liked songs button */\r\n");
      out.write("        .btn-toggle-like.liked {\r\n");
      out.write("            background: #ff3b30; /* Red for liked */\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-toggle-like:not(.liked) {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1); /* Lighter background when not liked */\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-toggle-like:not(.liked):hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Playlist Modal Styles */\r\n");
      out.write("        .playlist-modal-container {\r\n");
      out.write("            display: none; /* Hidden by default */\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            z-index: 10000;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: rgba(0,0,0,0.7);\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .playlist-modal-content {\r\n");
      out.write("            background-color: #282828;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .playlist-modal-content h3 {\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .playlist-modal-list {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            max-height: 300px;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .playlist-modal-list li {\r\n");
      out.write("            background: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .playlist-modal-list li:hover {\r\n");
      out.write("            background: #34C759;\r\n");
      out.write("        }\r\n");
      out.write("        .playlist-modal-close {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background: #555;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"song-modal-overlay\" onclick=\"closeModal(event)\">\r\n");
      out.write("        <div class=\"song-modal-content\" onclick=\"event.stopPropagation()\">\r\n");
      out.write("            <button class=\"modal-close-btn\" onclick=\"window.history.back()\">&times;</button>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"song-detail-container\">\r\n");
      out.write("                <img id=\"albumArt\" class=\"song-album-art\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.imageUrl}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Album Art\" />\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"song-info-section\">\r\n");
      out.write("                    <h1 class=\"song-detail-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("                    <p class=\"song-detail-artist\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.artist}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"song-metadata\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Spotify 웹 플레이어 임베드 -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"action-buttons\">\r\n");
      out.write("                    <button class=\"action-button btn-add-playlist\" onclick=\"openPlaylistModal()\">플레이리스트에 추가</button>\r\n");
      out.write("                    <button id=\"toggleLikeButton\" class=\"action-button btn-toggle-like\" onclick=\"toggleLike()\">좋아요 ♥</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Playlist Selection Modal -->\r\n");
      out.write("    <div id=\"playlistModal\" class=\"playlist-modal-container\">\r\n");
      out.write("        <div class=\"playlist-modal-content\">\r\n");
      out.write("            <h3>내 플레이리스트</h3>\r\n");
      out.write("            <ul id=\"playlistModalList\" class=\"playlist-modal-list\">\r\n");
      out.write("                <!-- Playlists will be dynamically inserted here -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <button class=\"playlist-modal-close\" onclick=\"closePlaylistModal()\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        const trackSpotifyId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.spotifyId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("        function closeModal(event) {\r\n");
      out.write("            if (event.target.classList.contains('song-modal-overlay')) {\r\n");
      out.write("                window.history.back();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function openPlaylistModal() {\r\n");
      out.write("            fetch(\"playlist.do\")\r\n");
      out.write("                .then(response => {\r\n");
      out.write("                    if (!response.ok) {\r\n");
      out.write("                        throw new Error(\"플레이리스트를 불러오는 데 실패했습니다. 다시 로그인해주세요.\");\r\n");
      out.write("                    }\r\n");
      out.write("                    return response.json();\r\n");
      out.write("                })\r\n");
      out.write("                .then(playlists => {\r\n");
      out.write("                    const playlistList = document.getElementById(\"playlistModalList\");\r\n");
      out.write("                    playlistList.innerHTML = \"\"; // Clear previous list\r\n");
      out.write("                    \r\n");
      out.write("                    if (playlists.length === 0) {\r\n");
      out.write("                        playlistList.innerHTML = '<li>플레이리스트가 없습니다. 먼저 플레이리스트를 만들어주세요.</li>';\r\n");
      out.write("                    } else {\r\n");
      out.write("                        playlists.forEach(playlist => {\r\n");
      out.write("                            const li = document.createElement(\"li\");\r\n");
      out.write("                            li.textContent = playlist.name;\r\n");
      out.write("                            li.onclick = () => addSongToSpecificPlaylist(playlist.id);\r\n");
      out.write("                            playlistList.appendChild(li);\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    document.getElementById(\"playlistModal\").style.display = \"flex\";\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => {\r\n");
      out.write("                    alert(error.message);\r\n");
      out.write("                });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function closePlaylistModal() {\r\n");
      out.write("            document.getElementById(\"playlistModal\").style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function addSongToSpecificPlaylist(playlistId) {\r\n");
      out.write("            const params = new URLSearchParams();\r\n");
      out.write("            params.append('action', 'addSong');\r\n");
      out.write("            params.append('playlistId', playlistId);\r\n");
      out.write("            params.append('trackSpotifyId', trackSpotifyId);\r\n");
      out.write("\r\n");
      out.write("            fetch(\"playlist.do\", {\r\n");
      out.write("                method: \"POST\",\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded'\r\n");
      out.write("                },\r\n");
      out.write("                body: params\r\n");
      out.write("            })\r\n");
      out.write("            .then(response => response.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                alert(data.message);\r\n");
      out.write("                if (data.success) {\r\n");
      out.write("                    closePlaylistModal();\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                console.error(\"Error adding song:\", error);\r\n");
      out.write("                alert(\"오류가 발생했습니다.\");\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 앨범 아트 회전 애니메이션 (재생 중일 때)\r\n");
      out.write("        const albumArt = document.getElementById('albumArt');\r\n");
      out.write("        const iframe = document.querySelector('.spotify-embed');\r\n");
      out.write("        \r\n");
      out.write("        if (iframe) {\r\n");
      out.write("            iframe.addEventListener('load', function() {\r\n");
      out.write("                albumArt.classList.add('playing');\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // --- New Like Functionality ---\r\n");
      out.write("        const toggleLikeButton = document.getElementById('toggleLikeButton');\r\n");
      out.write("        const userId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // Assuming userId is available in session\r\n");
      out.write("\r\n");
      out.write("        // Function to check initial like status\r\n");
      out.write("        async function checkLikeStatus() {\r\n");
      out.write("            if (!userId || userId === \"0\") { // userId is 0 if not logged in\r\n");
      out.write("                // If not logged in, disable like button or hide it. For now, just don't check.\r\n");
      out.write("                // toggleLikeButton.disabled = true;\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            try {\r\n");
      out.write("                const encodedSpotifyId = encodeURIComponent(trackSpotifyId);\r\n");
      out.write("                const response = await fetch(\"likedSongs.do?action=checkLike&spotifyId=\" + encodedSpotifyId, {\r\n");
      out.write("                    method: 'GET'\r\n");
      out.write("                });\r\n");
      out.write("                const data = await response.json();\r\n");
      out.write("                if (data.success) {\r\n");
      out.write("                    updateLikeButton(data.isLiked);\r\n");
      out.write("                } else {\r\n");
      out.write("                    console.error(\"Failed to check like status:\", data.message);\r\n");
      out.write("                }\r\n");
      out.write("            } catch (error) {\r\n");
      out.write("                console.error(\"Error checking like status:\", error);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Function to update the button's appearance\r\n");
      out.write("        function updateLikeButton(isLiked) {\r\n");
      out.write("            if (isLiked) {\r\n");
      out.write("                toggleLikeButton.classList.add('liked');\r\n");
      out.write("                toggleLikeButton.innerHTML = '좋아요 ♥'; // Filled heart or similar\r\n");
      out.write("            } else {\r\n");
      out.write("                toggleLikeButton.classList.remove('liked');\r\n");
      out.write("                toggleLikeButton.innerHTML = '좋아요 ♡'; // Empty heart\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Function to toggle like status\r\n");
      out.write("        async function toggleLike() {\r\n");
      out.write("            if (!userId || userId === \"0\") {\r\n");
      out.write("                alert(\"로그인이 필요합니다.\");\r\n");
      out.write("                window.location.href = \"loginForm.do\"; // Redirect to login page\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const currentIsLiked = toggleLikeButton.classList.contains('liked');\r\n");
      out.write("            const action = currentIsLiked ? 'remove' : 'add';\r\n");
      out.write("\r\n");
      out.write("            try {\r\n");
      out.write("                const encodedSpotifyId = encodeURIComponent(trackSpotifyId); // Moved outside\r\n");
      out.write("                const response = await fetch('likedSongs.do', {\r\n");
      out.write("                    method: 'POST',\r\n");
      out.write("                    headers: {\r\n");
      out.write("                        'Content-Type': 'application/x-www-form-urlencoded'\r\n");
      out.write("                    },\r\n");
      out.write("                    body: \"action=\" + action + \"&spotifyId=\" + encodedSpotifyId\r\n");
      out.write("                });\r\n");
      out.write("                const data = await response.json();\r\n");
      out.write("\r\n");
      out.write("                if (data.success) {\r\n");
      out.write("                    updateLikeButton(!currentIsLiked); // Toggle button state\r\n");
      out.write("                    alert(data.message);\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"좋아요 처리 실패: \" + data.message);\r\n");
      out.write("                }\r\n");
      out.write("            } catch (error) {\r\n");
      out.write("                console.error(\"Error toggling like:\", error);\r\n");
      out.write("                alert(\"좋아요 처리 중 오류가 발생했습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Initial check on page load\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', checkLikeStatus);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/song/songDetail.jsp(308,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty song.duration}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                            <div class=\"metadata-item\">\r\n");
        out.write("                                <span class=\"metadata-label\">재생시간</span>\r\n");
        out.write("                                <span class=\"metadata-value\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.duration}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("                            </div>\r\n");
        out.write("                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/song/songDetail.jsp(314,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty song.releaseDate}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                            <div class=\"metadata-item\">\r\n");
        out.write("                                <span class=\"metadata-label\">발매일</span>\r\n");
        out.write("                                <span class=\"metadata-value\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.releaseDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("                            </div>\r\n");
        out.write("                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/views/song/songDetail.jsp(324,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty song.spotifyId}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    <iframe \r\n");
        out.write("                        class=\"spotify-embed\"\r\n");
        out.write("                        src=\"https://open.spotify.com/embed/track/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${song.spotifyId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("?utm_source=generator&theme=0\" \r\n");
        out.write("                        frameBorder=\"0\" \r\n");
        out.write("                        allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" \r\n");
        out.write("                        loading=\"lazy\">\r\n");
        out.write("                    </iframe>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
